### PR TITLE
Fix `setClient` issue for new guzzle version

### LINKED ISSUE #380: Goutte\Client::setClient() does not exist
Having the following requirements in `require-dev` in `composer.json`: 

```json
        "atoum/atoum": "^4.0", (4.0.3)
        "behat/behat": "^3.8", (v3.10.0)
        "behat/mink-browserkit-driver": "^2.0", (v2.0.0)
        "behat/mink-goutte-driver": "^2.0", (v2.0.0)
        "behat/mink-selenium2-driver": "^1.5", (v1.5.0)
```

Running `php vendor/bin/behat` instantly crashes on: 

```shell
In GoutteFactory.php line 117:

  Method Goutte\Client::setClient() does not exist  
```

Function causing the Exception https://github.com/Behat/MinkExtension/blob/ba8ba8bde58b168f409c7c1e8e4b906c12856124/src/Behat/MinkExtension/ServiceContainer/Driver/GoutteFactory.php#L117

Function:

```php
    private function isGoutte1()
    {
        $refl = new \ReflectionParameter(array('Goutte\Client', 'setClient'), 0);

        $type = $refl->getType();
        if ($type instanceof \ReflectionNamedType && 'Guzzle\Http\ClientInterface' === $type->getName()) {
            return true;
        }

        return false;
    }
```

Now, `Goutte\Client` is an empty class which extends `Symfony\Component\BrowserKit\HttpBrowser` which in turn extends `Symfony\Component\BrowserKit\AbstractBrowser`. 

Neither of the parent classes indeed have the function `setClient`. 

What can I do to work around this for now or create a fix?

### PR DESCRIPTION
**Pull request by joshlopes**
Fix #380

### CODE REVIEW

**Comment by newscientistgeeks** [comment]
Can this one be merged? We've got same problems here about the way how the GoutteDriver is being created

**Comment by coderste** [comment]
+1 on this being merged. Having an issue where my codebase is throwing this error at me:
```
In GoutteFactory.php line 117:

  Method Goutte\Client::setClient() does not exist

```

And I believe this PR would fix that

**Comment by mahdi-khanzadi** [comment]
is there any chance to merge ?

**Comment by llagerlof** [comment]
I patched this pull request locally, but didn't worked for me. The error persists. I hope it works for you guys.

**Pull request closed without merging**
