### PR TITLE
Traduzido para o pt-BR

### PR DESCRIPTION
**Pull request by acfreitas**
Translation was taken in MinkExtension and Gherkin by Lógos Educação.

### CODE REVIEW

**Comment by stof** [comment]
@acfreitas any chance to complete the translation work ?

**Comment by keviocastro** [comment]
I will continue the translation. It will be very useful to me.

**Comment by stof** [comment]
@keviocastro ping

**Comment by keviocastro** [comment]
@stof I am completing the translation.
One question:
Translation for i-fill-in-field-with.
  <source> <[CDATA [/ ^ (?: | I) fill in "(P <field> (?: [^"] | \\ ") *)" with: $ /]]> </ source >

What makes this step? Fill in the field as empty?

**Comment by keviocastro** [comment]
The work was completed in https://github.com/Behat/MinkExtension/pull/198

**Comment by stof** [comment]
@keviocastro no. It fills the field with the value given as a PyString. The scenario will look like this:

```gherkin
  When I fill in "Description" with:
    """
    Some long description
    going there
    """"
  And I do another thing
```

**Comment by stof** [comment]
Anyway, closing in favor of #198

**Pull request closed without merging**
