### PR TITLE
Fix Behat/MinkExtension#309 Firefox starts instead of Chrome

### LINKED ISSUE #309: Selenium2: Firefox is launched with browser_name: chrome since the latest release
The latest release includes this change in `Selenium2Factory` which for some reason makes Selenium run Firefox instead of Chrome.

```php
+   ->booleanNode('marionette')->defaultFalse()->end()
```

Config:

```yml
default:
  extensions:
    Behat\MinkExtension:
      browser_name: chrome
      selenium2:
        wd_host: "http://172.17.0.1:4444/wd/hub"
        capabilities:
          chrome:
            switches:
              - "--disable-gpu"
              - "--headless"
```

Selenium log **with** the mentioned change:

> Capabilities {browser: firefox, browserName: chrome, chrome.extensions: [], chrome.switches: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], chromeOptions: {args: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], extensions: []}, ignoreZoomSetting: false, **marionette: false**, name: Behat feature suite, tags: [php, PHP 5.6.31]} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.**firefox.XpiDriverService**)

Selenium log **without** the mentioned change:

> Capabilities {browser: firefox, browserName: chrome, chrome.extensions: [], chrome.switches: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], chromeOptions: {args: [--disable-gpu, --headless, --window-size=1920,1080, --whitelisted-ips=""], extensions: []}, ignoreZoomSetting: false, name: Behat feature suite, tags: [php, PHP 5.6.31]} matched class org.openqa.selenium.remote.server.ServicedSession$Factory (provider: org.openqa.selenium.**chrome.ChromeDriverService**)

### PR DESCRIPTION
**Pull request by attrib**
This should fix #309

### CODE REVIEW

**Comment by deviantintegral** [comment]
Works for me. Thanks!

**Comment by juampynr** [comment]
Thanks @attrib! :wave:

**Comment by NicoHaase** [comment]
Do you see any chance of merging this and releasing a new version soon?

**Comment by jon-acker** [comment]
Thank you @attrib !! Was pulling my hair out (what's left of it anyway) trying to find out why Firefox was suddenly being launched instead of chrome, having upgraded to 2.3

**Comment by juampynr** [comment]
An alternative to using this patch is to pin the version to v2.2:

composer require behat/mink-extension:v2.2

**Comment by bocharsky-bw** [comment]
Or just add a few lines to your `behat.yml.dist`:
```yaml
default:
    extensions:
        Behat\MinkExtension:
            selenium2:
                capabilities:
                    marionette: null
```

and use the latest version.

**Comment by ciaranmcnulty** [comment]
Does flipping the default have a BC implication?

**Comment by brummbar** [comment]
@ciaranmcnulty if you are using Firefox versions up to 47 then the `marionette` capability should be set to `false` (as discussed [thoroughly here](https://stackoverflow.com/questions/43272919/difference-between-webdriver-firefox-marionette-webdriver-gecko-driver)). So this change should break the BC in that case.
If you use a recent version of Firefox or Chrome you need to have the `marionette` capability set to `null` at least.

**Comment by pamil** [comment]
Any possibility to tag a patch release with this fix? Could I be of some help?

**Comment by pamil** [comment]
Thanks @stof! 🎉

**Comment by OskarStark** [comment]
can you guys please create a release to fix this issue?

**Comment by OskarStark** [comment]
@stof can you please create a patch release with this fix?

It is blocking/breaking a lot

**Comment by ciaranmcnulty** [comment]
I've released 2.3.1 including this fix

**Comment by OskarStark** [comment]
Thank you very much @ciaranmcnulty

**Pull request merged**
