### PR TITLE
Symfony 5 compatiblity

### PR DESCRIPTION
**Pull request by cdaguerre**

### CODE REVIEW

**Comment by chadyred** [comment]
Works as expected, thanks but their is another existing PR but yours seems more complete than https://github.com/Behat/MinkExtension/pull/355

**Comment by chadyred** [comment]
@stof Is it possible to take a look at this, simple to review ?

**Comment by mahalay** [comment]
Reached out to @stof, @everzet, and @ciaranmcnulty in Twitter - it could be possible that they're very busy with more important stuff.

**Comment by Guikingone** [comment]
Hi everyone 👋 

Any news about this PR? 🤔

**Comment by mahalay** [comment]
> Hi everyone wave
> 
> Any news about this PR?

Here's the workaround I use atm:

```
"require-dev": {
    "behat/mink-extension": "dev-upgrade/allow-symony-5 as 2.3"
},
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/chadyred/MinkExtension"
    }
]
```

**Comment by chadyred** [comment]
We waiting for it ;)

**Comment by I-Valchev** [comment]
Any updates yet?

**Comment by pamil** [comment]
This extension will be moved to @FriendsOfBehat organization soon. Please use `friends-of-behat/mink-extension` instead of `behat/mink-extension`, no need to change anything in the code except for this dependency.

**Comment by xurizaemon** [comment]
@pamil @everzet given https://github.com/Behat/MinkExtension/pull/360#issuecomment-631583136, should [Behat/MinkExtension](https://packagist.org/packages/behat/mink-extension) be marked abandoned in Packagist, in favour of [friends-of-behat/mink-extension](https://packagist.org/packages/friends-of-behat/mink-extension)?

**Pull request closed without merging**
