### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by DonCallisto**
This should fix travis

### CODE REVIEW

**Comment by DonCallisto** [comment]
Not sure why it is failing.
BTW we should stop supporting `php5.3` as behat/bahat has `php5.3.3` as minimum requirement (don't know if error will still be present with 5.3.3, but I suppose it will not)

**Comment by dunglas** [comment]
Fixed in #308.

**Comment by carlcasbolt** [comment]
Why has this not been closed as a duplicate?

**Comment by DonCallisto** [comment]
@carlcasbolt you're right, this can be closed. I'm gonna do it.

**Pull request closed without merging**
