### PR TITLE
Allow specifying custom Selenium2Driver class for extending.

### PR DESCRIPTION
**Pull request by zeyus**

### CODE REVIEW

**Comment by alexdesignworks** [comment]
👍  This would be really useful

**Comment by spolischook** [comment]
Did you know that you can use your own factory for custom driver?
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/TestFrameworkBundle/Behat/ServiceContainer/OroTestFrameworkExtension.php#L57

**Comment by stof** [comment]
I'm not a fan of making the class name customizable here. We don't encourage inheritance on our driver classes

**Comment by aik099** [comment]
If a new driver factory is need to be created to use custom driver, then it's fine. If driver class needs to be extended to add new functions, then why not send a PR to Mink to make it available to other community members as well.

**Comment by spolischook** [comment]
Ok. In my case I have ```waitForAjax``` method that can be used from anywhere - from Context || Element. Only 2 objects accessible from everywhere - Session and Driver. Session is hardcoded in MinkExtension and Driver that can be extendable. As for me choice is obvious.

**Comment by aik099** [comment]
If you can please post content of `waitForAjax` method and describe what it does.

Doesn't this approach work for you:

1. add new method in your custom FeatureContext class, that will get session and driver and do whatever is needed with it
2. make your given/when method call this new feature context method instead

**Comment by spolischook** [comment]
> If you can please post content of waitForAjax method and describe what it does.

[It is just javascript function](https://github.com/orocrm/platform/blob/763e8d510c75e7a33bc515d5427f4fe0312ddbad/src/Oro/Bundle/TestFrameworkBundle/Behat/Driver/OroSelenium2Driver.php#L211-L235) that determine if current page is ready for work or not. It's too specific for our application.

> add new method in your custom FeatureContext class, that will get session and driver and do whatever is needed with it

> make your given/when method call this new feature context method instead

No, it will be used a every even step, so the feature will not be readable.

**Comment by aik099** [comment]
> It's ok for contexts, but what about elements?

Any specific code example, where this can be used, that you can share?

> No, it will be used a every even step, so the feature will not be readable.

I see. A common problem for SPA websites, where you need to wait for AJAX requests to be finished before checking on page content.

In QA-Tools library, I've recommended before this is already taken care of and before searching for an element we make sure that page is done loading (ajax or not) : https://github.com/qa-tools/qa-tools/blob/master/library/QATools/QATools/PageObject/ElementLocator/WaitingElementLocator.php#L68. It's also easy to extend that class to change how page readiness state is checked.

**Comment by spolischook** [comment]
> Any specific code example, where this can be used, that you can share?

Select2Entity field - it need to search about entity in search field, then choose one from results - https://git.io/vPZGE

> In QA-Tools library

I investigated your code, and find out that you use Element API to wait for ajax. It's ok for elements, but in context I need to create random element, then ask it to whait, or duplicate this logic in context. However responsible for this check is still Driver layer, isn't it?

**Comment by aik099** [comment]
> However responsible for this check is still Driver layer, isn't it?

Yes. The locator class is just a middle layer that contains whichever custom logic needed for element waiting/finding. This way no matter where you need to find the element the locator can do this for you.

**Comment by spolischook** [comment]
>  This link now opens 404 page.

Sorry for that. Fixed link. https://git.io/vPZlJ

> The locator class is just a middle layer that contains whichever custom logic needed for element waiting/finding

I have this middleware in my application, however use ```Locator``` for wait for ajax in Contexts is confusing.
This is example of usage ```waitForAjax``` method in Context - https://git.io/vPZ84

**Comment by stof** [comment]
@spolischook you could put this in a utility function receiving the driver as argument, and then call ``waitForAjax($driver)`` instead of ``$driver->waitForAjax()``. Your function does not belong to the driver itself, as it relies only on the public API of the driver

> It's ok for elements, but in context I need to create random element, then ask it to whait, or duplicate this logic in context. However responsible for this check is still Driver layer, isn't it?

You don't need to use the Element API to wait btw. Waiting is part of the Session API. You don't need an element to use it.

And this JS code does not belong to the driver layer. It uses only the driver public API, which means it can be written outside the driver. Writing something inside the driver class is needed only to add new features in Mink relying on the internal implementation (Selenium, Goutte, etc..), which is not your case here. You are only using the Mink API.

**Comment by spolischook** [comment]
Composition over inheritance, ok.
I just want to say, that in some cases inheritance is a case, when it can't broke something.
And because ```Driver``` is common layer that other layers (Elements and Sessions) use, then I can simply extend Driver instead of add new layer.
Because, you know, that you can solve any problem just adding new layer, but not the problem of layers complexity.

**Comment by stof** [comment]
@spolischook if you add a new non-Mink method to the driver layer, you would also need to extend the session and element to expose this new method in the higher layer, unless you access the internal driver layer, which is not supposed to happen.

The **only** case where you should be using ``getDriver()`` in your testsuite is for cases where the Mink abstraction is not supporting your use case and you need to access the internal implementation of the driver directly to escape Mink. This means using ``->getDriver()->getWebDriverSession()`` to access Selenium2 or ``getDriver()->getClient()`` to access the BrowserKit client for instance.
Your case is not escaping Mink. It is using the Mink API to wait for a JS expression.
To implement such logic, you should not be replacing any place of Mink. you should be using Mink (and the Session, not the Driver) in a place in your own code (i.e. a layer on top of Mink, not a layer deep inside Mink).

Btw, note that we provide strictly no backward compatibility guarantee if you extend one of our classes and add new methods in them (i.e. new responsibilities in it). We may add new methods in our classes in any release depending of the need (this would prevent us from adding any new feature if doing so). So extending the driver to add your own logic in it makes it very fragile, as it can break at any update (and this is true for any library out there btw, when you start adding new responsibilities to their classes)

**Comment by aik099** [comment]
It also prevents you from using different driver on per-scenario basis.

**Comment by spolischook** [comment]
> you would also need to extend the session and element to expose this new method in the higher layer

I would be great but [Session locked in MinkExtension](https://git.io/vPnn0) and [Document in Session](https://github.com/minkphp/Mink/blob/a88582ed857ea9792519e723b73d40a399e2a221/src/Session.php#L44). It very strange use ```new DocumentElement``` in constructor, can it be deprecated in future?

> Your case is not escaping Mink. It is using the Mink API to wait for a JS expression.

Ok, I think I can delegate page object to wait for ajax, it would be more convenient. I'll work on this next time when add page layer to my application.
Thanks @stof

**Comment by spolischook** [comment]
> It also prevents you from using different driver on per-scenario basis.

Did you use this possibility ever? And why?
I can imagine that I can use several Context for one feature - one for UI tests and another for functional. But different driver in one Context - can't.

**Comment by stof** [comment]
> I would be great but Session locked in MinkExtension and Document in Session. It very strange use new DocumentElement in constructor, can it be deprecated in future?

no it won't. I'm sayign that your way of doing things would require to be able to do this as well, but it is not a supported way of using Mink (you are extending Mink, not using Mink, while you should just be using it)

**Comment by alexdesignworks** [comment]
I'm a bit late to the discussion, but my 2c.

> I'm not a fan of making the class name customizable here. We don't encourage inheritance on our driver classes

Behat is a tool used for business and, when the tests cannot be implemented because there is a shortage in functionality or bug, the business cannot wait until we discuss all these issues in PRs and (maybe) accept some solution. The business need to progress, tickets needs to be closed, tests need to pass (or we all be out of jobs as we will be perceived as 'too slow').

I just do not get why would you lock the class, especially if Symfony provides an ability to replace it, making all of us finding workarounds (hello `Reflection`).

Re DriverFactory: I need to overload 1 method in `Selenium2Driver` class, but now I would have to create own DriverFactory class as well? This feels like unnecessary complication for a such simple thing.

Finally, I'm pretty sure that this PR will not be accepted, but at least this conversation raises the awareness about lack of Behat's flexibility in some parts.

**Comment by aik099** [comment]
My apologies upfront, but fact, that business demands it doesn't means that architecturally unsound PR will be accepted.

To summarize:

* the proposed solution is: use composition over inheritance without ever changing Driver class and if needed creating custom driver factory
* creating custom driver factory isn't much of a problem considering rare need to do so and small time needed to make it happen

**Comment by stof** [comment]
I'm closing this PR, because it does not fit the way Mink is expected to be used, as outline in previous comments made by @aik099 and myself.

> I just do not get why would you lock the class, especially if Symfony provides an ability to replace it, making all of us finding workarounds (hello Reflection).

if we unlock everything, it becomes a maintenance nightmare, because we then must ensure backward compatibility for all possible ways to hack in our code (as everything becomes a potential extension point).
Note that Symfony itself also stopped making it dead easy to replace service classes (APIs for power users still allow it, but not easy APIs), because it caused more harm than good.

**Pull request closed without merging**
