### PR TITLE
Remove default values for capabilities

### LINKED ISSUE #175: browserstack driver does not support the "browser_version" capability
Looking at this page: https://www.browserstack.com/automate/php#configure-capabilities
it seems that I can use "browser_version".
But this is currently disdallowed in the configuration which the extension validates.
I tried using "version" instead but it does not seem to work

### PR DESCRIPTION
**Pull request by stof**
This lets Selenium choose its own default values without duplicating them.
Replaces #183 Closes #175
Refs #179

### CODE REVIEW

**Comment by stof** [comment]
@opalenet-olivier can you try my alternative to your PR to see if it fixes it ?

**Comment by opalenet-olivier** [comment]
It seems to work yes :)
I'll do some more tests with Browserstack, I'll let you know if I have some difficulties.

When do you think you'll make a new release ?

**Comment by Shine-neko** [comment]
@stof this does not work for me

**Comment by stof** [comment]
@Shine-neko please open an issue rather than commenting on a merged PR. this makes it much easier to manage.
And please provide details about your problem when opening the issue. ``this does not work for me`` is not debuggable.

**Pull request merged**
